import { useEffect, useState } from 'react'
import './App.css'
import { checkRyokoConnection } from './lib/supabase'
import { createTrip, getStoredSession, issueMember, joinTrip, listDays, subscribeToTripPresence } from './lib/ryoko'

type Day = { id?: string; date: string; city: string; emoji: string; title: string; items: string[] }
export default function App() {
  const [days, setDays] = useState<Day[]>([]); const [active, setActive] = useState(0); const [invite, setInvite] = useState(false); const [joinOpen, setJoinOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [startOpen, setStartOpen] = useState(!getStoredSession()); const [role, setRole] = useState('Editor'); const [inviteName, setInviteName] = useState(''); const [joinCode, setJoinCode] = useState(''); const [tripName, setTripName] = useState('Spring in Japan'); const [startDate, setStartDate] = useState('2026-04-18'); const [endDate, setEndDate] = useState('2026-05-02'); const [dragged, setDragged] = useState<number | null>(null); const [checked, setChecked] = useState<Record<string, boolean>>({}); const [copied, setCopied] = useState(false); const [online, setOnline] = useState(0); const [loading, setLoading] = useState(true)
  useEffect(() => { void checkRyokoConnection() }, [])
  useEffect(() => { const session = getStoredSession(); if (!session) { setLoading(false); return }; void listDays(session).then(remote => setDays(remote.map((day: { day_date: string; city: string | null; title: string | null }) => ({ date: day.day_date, city: day.city ?? 'Japan', emoji: '✦', title: day.title ?? 'A day to remember', items: [] })))).finally(() => setLoading(false)); return subscribeToTripPresence(session, members => setOnline(Math.max(1, members.length))) }, [])
  const toggle = (key: string) => setChecked(value => ({ ...value, [key]: !value[key] }))
  const addDay = () => { if (!getStoredSession()) { setJoinOpen(true); return }; const date = new Date().toISOString().slice(0, 10); setDays(current => [...current, { date, city: 'Japan', emoji: '✦', title: 'A new day to plan', items: [] }]); setActive(days.length) }
  const updateDay = (index: number, field: 'city' | 'title', value: string) => setDays(current => current.map((day, i) => i === index ? { ...day, [field]: value } : day))
  const dropDay = (target: number) => { if (dragged === null || dragged === target) return; setDays(current => { const next = [...current]; const [moved] = next.splice(dragged, 1); next.splice(target, 0, moved); return next }); setDragged(null) }
  const copy = () => { navigator.clipboard?.writeText('SAKURA-8Q'); setCopied(true); setTimeout(() => setCopied(false), 1500) }
  return <main className="shell">
    <header className="topbar"><button className="brand ghost" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><span>✿</span> ryōkō <small>旅行</small></button><button className="trip-switcher" onClick={() => setJoinOpen(true)}><i /> <b>Spring in Japan</b>⌄</button><div className="top-actions"><span className="save">● Saved just now</span><button className="ghost" onClick={() => setJoinOpen(true)} aria-label="Open trip settings">⚙</button><button className="avatar owner" onClick={() => setJoinOpen(true)} aria-label="Open profile">T</button></div></header>
    <section className="hero"><div><p className="eyebrow">YOUR SHARED JAPAN ITINERARY</p><h1>Our little <em>Japan</em> story <span>✦</span></h1><p className="subtitle">{loading ? 'Loading your adventure…' : days.length ? 'A shared place for all the places we’ll go.' : 'Join a trip to start planning together.'}</p></div><div className="actions"><button className="secondary" onClick={() => setJoinOpen(true)}>Join a trip</button><button className="primary" onClick={() => setInvite(true)}>＋ Add people</button></div></section>
    <section className="stats"><div><b>14</b><small>days planned</small></div><div><b>3</b><small>cities</small></div><div><b>7%</b><small>ready to roam</small></div><div className="collabs"><span className="avatar pink">M</span><span className="avatar blue">J</span><span className="avatar yellow">T</span><small>{online} collaborators online <i /></small></div></section>
    <div className="workspace"><section className="timeline-panel"><div className="heading"><div><p className="eyebrow">YOUR ITINERARY</p><h2>Let’s make it <em>happen</em>.</h2></div><button className="round" onClick={addDay} aria-label="Add a day">＋</button></div><div className="timeline">{days.map((day, index) => <article draggable className={`day ${active === index ? 'selected' : ''}`} key={`${day.id ?? day.date}-${index}`} onDragStart={() => setDragged(index)} onDragOver={event => event.preventDefault()} onDrop={() => dropDay(index)} onClick={() => setActive(index)}><div className="date"><b>{day.date.split('-')[2] ?? day.date.split(' ')[1] ?? day.date}</b><small>{day.date.split('-')[1] ?? day.date.split(' ')[0] ?? ''}</small></div><div className="card"><div className="card-top"><span className={`pill p${index}`}>{day.emoji} <input className="inline-input pill-input" value={day.city} onChange={e => updateDay(index, 'city', e.target.value)} onClick={e => e.stopPropagation()} /></span><span className="drag" title="Drag to reorder">⠿</span></div><input className="inline-input title-input" value={day.title} onChange={e => updateDay(index, 'title', e.target.value)} onClick={e => e.stopPropagation()} />{day.items.map((item, itemIndex) => <label key={item}><input type="checkbox" checked={!!checked[`${index}-${itemIndex}`]} onChange={() => toggle(`${index}-${itemIndex}`)} onClick={e => e.stopPropagation()} />{item}</label>)}</div></article>)}</div>{!loading && !days.length && <p className="empty-state">No days yet. Start by adding your first day to the shared journey.</p>}<button className="add-day" onClick={addDay}>＋ Add another day</button></section>
      <aside className="map-panel"><div className="heading"><div><p className="eyebrow">THE BIG PICTURE</p><h2>Wander <em>here</em> ↗</h2></div><button className="round" onClick={() => setActive(0)} aria-label="Center map">⌖</button></div><div className="map"><div className="mountain">⌁</div><div className="route" /><button className="pin tokyo" onClick={() => setActive(Math.min(0, days.length - 1))}>✦<small>Tokyo</small></button><button className="pin kyoto" onClick={() => setActive(Math.min(2, Math.max(0, days.length - 1)))}>✦<small>Kyoto</small></button><button className="pin osaka" onClick={() => setActive(Math.min(1, Math.max(0, days.length - 1)))}>✦<small>Osaka</small></button><span className="japan">JAPAN<br /><small>本州</small></span></div><div className="legend">● 3 cities　〰 your route</div><div className="tip">🌸 <b>Golden week tip</b><br /><span>Book trains a little early — future you will be grateful.</span></div></aside></div>
    <footer><span>Made with a little bit of ✿ and a lot of excitement.</span><span>Trip code <button onClick={copy}>{copied ? 'Copied!' : 'SAKURA-8Q'} ↗</button></span></footer>
    {invite && <div className="backdrop" onClick={() => setInvite(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setInvite(false)}>×</button><span className="flower">✿</span><p className="eyebrow">INVITE A TRAVEL BUDDY</p><h2>More is more <em>fun.</em></h2><p className="modal-copy">Create a personal access code for someone joining the adventure.</p><label>Name<input placeholder="e.g. Alex" value={inviteName} onChange={e => setInviteName(e.target.value)} autoFocus /></label><label>Access level<select value={role} onChange={e => setRole(e.target.value)}><option>Editor</option><option>Viewer</option></select></label><button className="primary full" onClick={async () => { const session = getStoredSession(); if (session && inviteName) await issueMember(session, inviteName, role.toLowerCase() as 'editor' | 'viewer', '#df8f9b'); setInvite(false) }}>Generate {role} code ✦</button></div></div>}
    {joinOpen && <div className="backdrop" onClick={() => setJoinOpen(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setJoinOpen(false)}>×</button><span className="flower">✿</span><p className="eyebrow">JOIN A SHARED TRIP</p><h2>Let’s go <em>together.</em></h2><p className="modal-copy">Use your personal access code to open the live itinerary.</p><label>Your name<input placeholder="e.g. Terry" value={inviteName} onChange={e => setInviteName(e.target.value)} autoFocus /></label><label>Access code<input placeholder="8 character code" value={joinCode} onChange={e => setJoinCode(e.target.value)} /></label><button className="primary full" onClick={async () => { if (!joinCode || !inviteName) return; await joinTrip(joinCode, inviteName); window.location.reload() }}>Join trip ✦</button></div></div>}
    {startOpen && <div className="backdrop"><div className="modal choice-modal"><span className="flower">✿</span><p className="eyebrow">WELCOME TO RYŌKŌ</p><h2>Where are we <em>going?</em></h2><p className="modal-copy">Choose how you want to begin. Your journey will be live and shared.</p><button className="primary full" onClick={() => { setStartOpen(false); setJoinOpen(true) }}>Rejoin a journey</button><button className="secondary full" onClick={() => { setStartOpen(false); setCreateOpen(true) }}>Start a new journey</button></div></div>}
    {createOpen && <div className="backdrop"><div className="modal"><span className="flower">✿</span><p className="eyebrow">START A NEW JOURNEY</p><h2>Plan something <em>lovely.</em></h2><label>Trip name<input value={tripName} onChange={e => setTripName(e.target.value)} autoFocus /></label><label>Your name<input value={inviteName} onChange={e => setInviteName(e.target.value)} placeholder="e.g. Terry" /></label><label>Dates<div className="date-fields"><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /><input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} /></div></label><button className="primary full" onClick={async () => { if (!tripName || !inviteName) return; await createTrip(tripName, startDate, endDate, inviteName); window.location.reload() }}>Create journey ✦</button></div></div>}
  </main>
}
