import { useEffect, useState } from 'react'
import './App.css'
import { checkRyokoConnection } from './lib/supabase'

type Day = { date: string; city: string; emoji: string; title: string; items: string[] }
const initialDays: Day[] = [
  { date: 'APR 18', city: 'Tokyo', emoji: '🗼', title: 'Neon nights & tiny alleys', items: ['Shibuya crossing at golden hour', 'Dinner at an izakaya in Ebisu'] },
  { date: 'APR 19', city: 'Tokyo', emoji: '🍣', title: 'Old Tokyo, new memories', items: ['Senso-ji temple before breakfast', 'Save an Instagram spot'] },
  { date: 'APR 22', city: 'Kyoto', emoji: '⛩️', title: 'Bamboo, tea & quiet paths', items: ['Arashiyama bamboo grove', 'Tea ceremony in Gion'] },
]

export default function App() {
  const [days] = useState(initialDays); const [active, setActive] = useState(0); const [invite, setInvite] = useState(false); const [role, setRole] = useState('Editor'); const [checked, setChecked] = useState<Record<string, boolean>>({ '0-0': true }); const [copied, setCopied] = useState(false)
  useEffect(() => { void checkRyokoConnection() }, [])
  const toggle = (key: string) => setChecked(value => ({ ...value, [key]: !value[key] }))
  const copy = () => { navigator.clipboard?.writeText('SAKURA-8Q'); setCopied(true); setTimeout(() => setCopied(false), 1500) }
  return <main className="shell">
    <header className="topbar"><div className="brand"><span>✿</span> ryōkō <small>旅行</small></div><div className="trip-switcher"><i /> <b>Spring in Japan</b>⌄</div><div className="top-actions"><span className="save">● Saved just now</span><button className="ghost">⚙</button><button className="avatar owner">T</button></div></header>
    <section className="hero"><div><p className="eyebrow">APR 18 — MAY 02, 2025 · 14 DAYS</p><h1>Our little <em>Japan</em> story <span>✦</span></h1><p className="subtitle">A shared place for all the places we’ll go.</p></div><div className="actions"><button className="secondary" onClick={() => setInvite(true)}>＋ Add people</button><button className="primary" onClick={() => setInvite(true)}>Share trip ↗</button></div></section>
    <section className="stats"><div><b>14</b><small>days planned</small></div><div><b>3</b><small>cities</small></div><div><b>7%</b><small>ready to roam</small></div><div className="collabs"><span className="avatar pink">M</span><span className="avatar blue">J</span><span className="avatar yellow">T</span><small>3 collaborators online <i /></small></div></section>
    <div className="workspace"><section className="timeline-panel"><div className="heading"><div><p className="eyebrow">YOUR ITINERARY</p><h2>Let’s make it <em>happen</em>.</h2></div><button className="round">＋</button></div><div className="timeline">{days.map((day, index) => <article className={`day ${active === index ? 'selected' : ''}`} key={day.date} onClick={() => setActive(index)}><div className="date"><b>{day.date.split(' ')[1]}</b><small>{day.date.split(' ')[0]}</small></div><div className="card"><div className="card-top"><span className={`pill p${index}`}>{day.emoji} {day.city}</span><span className="drag">⠿</span></div><h3>{day.title}</h3>{day.items.map((item, itemIndex) => <label key={item}><input type="checkbox" checked={!!checked[`${index}-${itemIndex}`]} onChange={() => toggle(`${index}-${itemIndex}`)} onClick={e => e.stopPropagation()} />{item}</label>)}{index === 0 && <div className="insta"><span className="insta-art">⌁<small>渋谷</small></span><span><b>Saved from Instagram</b><small>@tokyofooddiary · Shibuya</small></span><i>↗</i></div>}</div></article>)}</div><button className="add-day">＋ Add another day</button></section>
      <aside className="map-panel"><div className="heading"><div><p className="eyebrow">THE BIG PICTURE</p><h2>Wander <em>here</em> ↗</h2></div><button className="round">⌖</button></div><div className="map"><div className="mountain">⌁</div><div className="route" /><button className="pin tokyo" onClick={() => setActive(0)}>✦<small>Tokyo</small></button><button className="pin kyoto" onClick={() => setActive(2)}>✦<small>Kyoto</small></button><button className="pin osaka">✦<small>Osaka</small></button><span className="japan">JAPAN<br /><small>本州</small></span></div><div className="legend">● 3 cities　〰 your route</div><div className="tip">🌸 <b>Golden week tip</b><br /><span>Book trains a little early — future you will be grateful.</span></div></aside></div>
    <footer><span>Made with a little bit of ✿ and a lot of excitement.</span><span>Trip code <button onClick={copy}>{copied ? 'Copied!' : 'SAKURA-8Q'} ↗</button></span></footer>
    {invite && <div className="backdrop" onClick={() => setInvite(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setInvite(false)}>×</button><span className="flower">✿</span><p className="eyebrow">INVITE A TRAVEL BUDDY</p><h2>More is more <em>fun.</em></h2><p className="modal-copy">Create a personal access code for someone joining the adventure.</p><label>Name<input placeholder="e.g. Alex" autoFocus /></label><label>Access level<select value={role} onChange={e => setRole(e.target.value)}><option>Editor</option><option>Viewer</option></select></label><button className="primary full" onClick={() => setInvite(false)}>Generate {role} code ✦</button></div></div>}
  </main>
}
